version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    depends_on:
      - postgres
  postgres:
    image: "postgres:15.3-alpine"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
  pgAdmin:
    image: "dpage/pgadmin4:latest"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgres

networks:
  default:
    name: local-network
    driver: bridge
