version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - PORT=3000
      - DATABASE_URL=''
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    depends_on:
      - postgres
  pgAdmin:
    image: 'dpage/pgadmin4:latest'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgres

networks:
  default:
    name: local-network
    driver: bridge
